# Generated by Django 6.0.1 on 2026-03-04 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ptms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_evento', models.DateField()),
                ('descricao', models.TextField()),
                ('ptm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ptms.ptm')),
                ('status_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.statusobra')),
                ('status_ptm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.statusptm')),
            ],
            options={
                'ordering': ('data_evento', 'id'),
            },
        ),
    ]
