# Generated by Django 6.0.1 on 2026-03-04 19:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ptms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoPTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcela', models.CharField(choices=[('1', '1a'), ('2', '2a'), ('3', '3a'), ('4', '4a')], max_length=2)),
                ('tipo_registro', models.CharField(choices=[('normal', 'Normal'), ('extra', 'Extra')], default='normal', max_length=10)),
                ('dt_solicitacao', models.DateField(blank=True, null=True)),
                ('dt_envio_pg', models.DateField(blank=True, null=True)),
                ('dt_pagamento', models.DateField(blank=True, null=True)),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('numero_ob', models.CharField(blank=True, max_length=50)),
                ('numero_empenho', models.CharField(blank=True, max_length=50)),
                ('observacao', models.TextField(blank=True)),
                ('ptm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='ptms.ptm')),
            ],
            options={
                'ordering': ('ptm', 'parcela', 'dt_pagamento', 'id'),
            },
        ),
    ]
