# Generated by Django 6.0.1 on 2026-03-04 19:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordem', models.CharField(max_length=30, unique=True)),
                ('regiao', models.CharField(max_length=120)),
                ('municipio', models.CharField(max_length=120)),
                ('projeto', models.TextField()),
                ('projeto_detalhado', models.TextField(blank=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('teto_fem', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('investimento_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('recurso_fem', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rendimentos_fem', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('contrapartida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ressalva', models.TextField(blank=True)),
                ('conta_ptm', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('populacao_beneficiada', models.PositiveIntegerField(blank=True, null=True)),
                ('area_investimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.areainvestimento')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.secretaria')),
                ('status_obra_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ptms_status_obra', to='core.statusobra')),
                ('status_ptm_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ptms_status_ptm', to='core.statusptm')),
                ('tipo_fem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipofem')),
            ],
            options={
                'ordering': ('ordem',),
            },
        ),
    ]
