# Generated by Django 5.2.8 on 2026-03-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptms', '0007_termo_adesao_catalog_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptm',
            name='deputado',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ptm',
            name='numero_emenda',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
