from django.urls import path

from ptms.views import (
    PTMCreateView,
    PTMDeleteView,
    PTMDetailView,
    PTMListView,
    PTMUpdateView,
    conclusao_create,
    conclusao_delete,
    conclusao_update,
    evento_create,
    observacao_create,
    observacao_delete,
    observacao_update,
    pagamento_create,
    pagamento_delete,
    pagamento_update,
    prestacao_delete,
    prestacao_historico_delete,
    prestacao_historico_create,
    prestacao_historico_update,
    prestacao_upsert,
    vistoria_delete,
    vistoria_create,
    vistoria_update,
)

urlpatterns = [
    path('', PTMListView.as_view(), name='ptm_list'),
    path('ptms/novo/', PTMCreateView.as_view(), name='ptm_create'),
    path('ptms/<int:pk>/', PTMDetailView.as_view(), name='ptm_detail'),
    path('ptms/<int:pk>/editar/', PTMUpdateView.as_view(), name='ptm_update'),
    path('ptms/<int:pk>/excluir/', PTMDeleteView.as_view(), name='ptm_delete'),

    path('ptms/<int:ptm_id>/eventos/novo/', evento_create, name='evento_create'),
    path('ptms/<int:ptm_id>/pagamentos/novo/', pagamento_create, name='pagamento_create'),
    path('ptms/<int:ptm_id>/pagamentos/<int:pagamento_id>/editar/', pagamento_update, name='pagamento_update'),
    path('ptms/<int:ptm_id>/pagamentos/<int:pagamento_id>/excluir/', pagamento_delete, name='pagamento_delete'),
    path('ptms/<int:ptm_id>/vistorias/novo/', vistoria_create, name='vistoria_create'),
    path('ptms/<int:ptm_id>/vistorias/<int:vistoria_id>/editar/', vistoria_update, name='vistoria_update'),
    path('ptms/<int:ptm_id>/vistorias/<int:vistoria_id>/excluir/', vistoria_delete, name='vistoria_delete'),
    path('ptms/<int:ptm_id>/prestacao/editar/', prestacao_upsert, name='prestacao_upsert'),
    path('ptms/<int:ptm_id>/prestacao/excluir/', prestacao_delete, name='prestacao_delete'),
    path('ptms/<int:ptm_id>/prestacao/historico/novo/', prestacao_historico_create, name='prestacao_historico_create'),
    path('ptms/<int:ptm_id>/prestacao/historico/<int:historico_id>/editar/', prestacao_historico_update, name='prestacao_historico_update'),
    path('ptms/<int:ptm_id>/prestacao/historico/<int:historico_id>/excluir/', prestacao_historico_delete, name='prestacao_historico_delete'),
    path('ptms/<int:ptm_id>/observacoes/novo/', observacao_create, name='observacao_create'),
    path('ptms/<int:ptm_id>/observacoes/<int:observacao_id>/editar/', observacao_update, name='observacao_update'),
    path('ptms/<int:ptm_id>/observacoes/<int:observacao_id>/excluir/', observacao_delete, name='observacao_delete'),
    path('ptms/<int:ptm_id>/conclusoes/novo/', conclusao_create, name='conclusao_create'),
    path('ptms/<int:ptm_id>/conclusoes/<int:conclusao_id>/editar/', conclusao_update, name='conclusao_update'),
    path('ptms/<int:ptm_id>/conclusoes/<int:conclusao_id>/excluir/', conclusao_delete, name='conclusao_delete'),
]
