from django.urls import path

from ptms.views import (
    DashboardView,
    NotaTecnicaMunicipioListView,
    PTMCreateView,
    PTMDeleteView,
    PTMDetailView,
    PTMListView,
    PTMPublicDetailView,
    PTMUpdateView,
    conclusao_create,
    conclusao_delete,
    conclusao_update,
    evento_create,
    evento_delete,
    evento_update,
    observacao_create,
    observacao_delete,
    observacao_update,
    pagamento_create,
    pagamento_delete,
    pagamento_update,
    prestacao_delete,
    prestacao_historico_delete,
    prestacao_historico_create,
    prestacao_historico_update,
    prestacao_upsert,
    ptm_generate_public_link,
    ptm_status_analise_update,
    ptm_public_upload,
    nota_tecnica_detail,
    termo_adesao_delete,
    termo_adesao_upsert,
    vistoria_delete,
    vistoria_create,
    vistoria_update,
)

urlpatterns = [
    path('', PTMListView.as_view(), name='ptm_list'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('notas-tecnicas/', NotaTecnicaMunicipioListView.as_view(), name='nota_tecnica_select'),
    path('notas-tecnicas/gerar/', nota_tecnica_detail, name='nota_tecnica_detail'),
    path('acesso/<slug:token>/', PTMPublicDetailView.as_view(), name='ptm_public_detail'),
    path('acesso/<slug:token>/upload/', ptm_public_upload, name='ptm_public_upload'),
    path('ptms/novo/', PTMCreateView.as_view(), name='ptm_create'),
    path('ptms/<int:pk>/', PTMDetailView.as_view(), name='ptm_detail'),
    path('ptms/<int:pk>/editar/', PTMUpdateView.as_view(), name='ptm_update'),
    path('ptms/<int:pk>/excluir/', PTMDeleteView.as_view(), name='ptm_delete'),
    path('ptms/<int:pk>/gerar-link-publico/', ptm_generate_public_link, name='ptm_generate_public_link'),
    path('ptms/<int:pk>/status-analise-documentacao/', ptm_status_analise_update, name='ptm_status_analise_update'),

    path('ptms/<int:ptm_id>/eventos/novo/', evento_create, name='evento_create'),
    path('ptms/<int:ptm_id>/eventos/<int:evento_id>/editar/', evento_update, name='evento_update'),
    path('ptms/<int:ptm_id>/eventos/<int:evento_id>/excluir/', evento_delete, name='evento_delete'),
    path('ptms/<int:ptm_id>/termo-adesao/editar/', termo_adesao_upsert, name='termo_adesao_upsert'),
    path('ptms/<int:ptm_id>/termo-adesao/excluir/', termo_adesao_delete, name='termo_adesao_delete'),
    path('ptms/<int:ptm_id>/pagamentos/novo/', pagamento_create, name='pagamento_create'),
    path('ptms/<int:ptm_id>/pagamentos/<int:pagamento_id>/editar/', pagamento_update, name='pagamento_update'),
    path('ptms/<int:ptm_id>/pagamentos/<int:pagamento_id>/excluir/', pagamento_delete, name='pagamento_delete'),
    path('ptms/<int:ptm_id>/vistorias/novo/', vistoria_create, name='vistoria_create'),
    path('ptms/<int:ptm_id>/vistorias/<int:vistoria_id>/editar/', vistoria_update, name='vistoria_update'),
    path('ptms/<int:ptm_id>/vistorias/<int:vistoria_id>/excluir/', vistoria_delete, name='vistoria_delete'),
    path('ptms/<int:ptm_id>/prestacao/editar/', prestacao_upsert, name='prestacao_upsert'),
    path('ptms/<int:ptm_id>/prestacao/excluir/', prestacao_delete, name='prestacao_delete'),
    path('ptms/<int:ptm_id>/prestacao/historico/novo/', prestacao_historico_create, name='prestacao_historico_create'),
    path('ptms/<int:ptm_id>/prestacao/historico/<int:historico_id>/editar/', prestacao_historico_update, name='prestacao_historico_update'),
    path('ptms/<int:ptm_id>/prestacao/historico/<int:historico_id>/excluir/', prestacao_historico_delete, name='prestacao_historico_delete'),
    path('ptms/<int:ptm_id>/observacoes/novo/', observacao_create, name='observacao_create'),
    path('ptms/<int:ptm_id>/observacoes/<int:observacao_id>/editar/', observacao_update, name='observacao_update'),
    path('ptms/<int:ptm_id>/observacoes/<int:observacao_id>/excluir/', observacao_delete, name='observacao_delete'),
    path('ptms/<int:ptm_id>/conclusoes/novo/', conclusao_create, name='conclusao_create'),
    path('ptms/<int:ptm_id>/conclusoes/<int:conclusao_id>/editar/', conclusao_update, name='conclusao_update'),
    path('ptms/<int:ptm_id>/conclusoes/<int:conclusao_id>/excluir/', conclusao_delete, name='conclusao_delete'),
]
