# Generated by Django 6.0.1 on 2026-03-04 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ptms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacaoEncaminhamentoPTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField()),
                ('origem', models.CharField(blank=True, max_length=120)),
                ('ptm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_enc', to='ptms.ptm')),
            ],
            options={
                'ordering': ('data', 'id'),
            },
        ),
    ]
