# Generated by Django 6.0.1 on 2026-03-04 19:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ptms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistoriaPTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dt_solicitacao', models.DateField(blank=True, null=True)),
                ('dt_resposta', models.DateField(blank=True, null=True)),
                ('percentual_execucao', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('observacao', models.TextField(blank=True)),
                ('ptm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='ptms.ptm')),
            ],
            options={
                'ordering': ('ptm', 'dt_solicitacao', 'id'),
            },
        ),
    ]
