# Generated by Django 6.0.1 on 2026-03-04 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ptms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestacaoContaPTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prazo_contas', models.DateField(blank=True, null=True)),
                ('data_prestacao', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, max_length=255)),
                ('ptm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestacao_conta', to='ptms.ptm')),
            ],
            options={
                'ordering': ('ptm',),
            },
        ),
        migrations.CreateModel(
            name='PrestacaoContaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField()),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='prestacao_contas.prestacaocontaptm')),
            ],
            options={
                'ordering': ('data', 'id'),
            },
        ),
    ]
